site_name: IDL Network
site_url: https://idlnetwork.org/
docs_dir: source
site_dir: docs
repo_url: https://github.com/NixImagery
repo_name: IDLNetwork
edit_uri: ""
theme:
  name: material
  custom_dir: overrides
  favicon: img/favicon.ico
  logo: img/anarchysm.gif
  features:
    - navigation.instant # protects the search index
    # - toc.integrate
    # - navigation.indexes
    # - navigation.tabs
    # - navigation.sections
  palette:
    scheme: idlnetwork
extra_css:
  - stylesheets/extra.css

nav: 
 - Introduction: index.md
 - Blog: _pages/*.md
 - Index: tags.md

plugins: 
  - search
  - literate-nav
  - tags:
      tags_file: tags.md
  - git-revision-date-localized
  - bibtex:
      bib_file: "/Users/v1nhood/Library/CloudStorage/Dropbox/Bibliographies/library.bib"
      csl_file: "/Users/v1nhood/Library/CloudStorage/Dropbox/styles/chicago-author-date-with-ibid.csl"
      cite_inline: true

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - footnotes
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      title: On this page

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/NixImagery
      name: The NixImagery Repository at GitHub
